Ensure you are using Python 3.0 and above

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE". Delete the 'raise NotImplementedError()' once you write your code there

In [1]:
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."

### Complete the following Python exercises and submit the notebook on class folder

In [2]:
# Imports
import numpy as np
from nose.tools import *
import IPython
assert IPython.version_info[0] >= 3, "Your version of IPython is too old, please update it."

### Part A - Python stuff

#### Question 1
Write a function that adds two numbers together. If the numbers result in decimals, make sure that they are rounded off to 2 significant decimals, i.e. 23.1234 + 12.4321 = 35.56

In [7]:
# warm up
def add_two_numbers(x,y):
    return round((x+y),2)

In [8]:
# Run tests
assert_equal= add_two_numbers(10.390, 10.9899)
print(assert_equal)


21.38


#### Question 2
Complete this function to provide the cummulative sum of the first N numbers. The numbers should be counted from 1,2,.... Tip: You may want to look at the range function of Python.
E.g. function(4) = 1+2+3+4 = 10

Add an additional check - if the number N provided is outside an acceptable range, return 0. The acceptable range is 0 - 200 inclusive (i.e. it includes 0 and 200)

In [15]:
def sum_first_N_numbers(N):
    if 0 <= N <= 200:
        return sum(range(1, N + 1))
    else:
        return 0


In [17]:
# Tests 1
result1 = sum_first_N_numbers(4)
print("Result for N=4:", result1)

Result for N=4: 10


In [18]:
# Tests 2
result2 = sum_first_N_numbers(0)
print("Result for N=0:", result2)

Result for N=0: 0


In [19]:
# Tests 3
result3 = sum_first_N_numbers(300)
print("Result for N=300:", result3)

Result for N=300: 0


#### Question 3
Write a function to calculate the mean of a list of numbers. Numbers should be rounded off to 2 significant decimals if they are decimal numbers

E.g. function([2,2,2,2]) = 2

In [10]:

def get_mean(x):
    if not x:
        return None
    else:
        mean = sum(x) / len(x)
        rounded_mean = round(mean, 2)
        return rounded_mean

In [11]:
# Tests 1
#assert_equal(get_mean([2,3,4,5]), 3.5)
numbers_list = [2, 3, 4, 5]
result = get_mean(numbers_list)
print(result)

3.5


#### Question 4
Complete the function to get the power of a number. Ensure that if it is a decimal number it is rounded off to 3 (THREE) decimal places. 

E.g. function(3,2) = 9

In [18]:
def get_i_power(x, i):
    result = x ** i

    if isinstance(result, float):
        result = round(result, 3)

    return result


16


In [20]:
# Test 1
#assert_equal(get_i_power(3,2), 9)
result = get_i_power(3, 2)
print(result)


9


In [21]:
# Tests 2
#assert_equal(get_i_power(2.6,5), 118.814)
result2 = get_i_power(2.6, 5)
print(result2)


118.814


#### Question 5
Write a function to reverse a string.

E.g. function('Mountain') = 'niatnuoM'

In [11]:
def reverse_string(s):
    return s[::-1]

In [12]:
reverse_string('Mount Meru')

'ureM tnuoM'

#### Question 6
Given the assignment_dates list, can you return the days from this string

E.g. function(assignment_dates) = ['Friday', 'Saturday', 'Sunday']

In [21]:
def get_day(date_list):
    return [(date.split()[-4]) for date in date_list]

In [22]:
assignment_dates = ['Friday 27 Jan 2017', 'Saturday 12 March 2016', 'Sunday 3 October 2015']
assert get_day(assignment_dates)
print(get_day(assignment_dates))

['Friday', 'Saturday', 'Sunday']


In [23]:
assignment_dates2 = ['Monday 17 Jan 2017', 'Tuesday 1 March 2016', 'Wednesday 30 October 2015']
assert get_day(assignment_dates2)
print(get_day(assignment_dates2))

['Monday', 'Tuesday', 'Wednesday']


In [24]:

assignment_dates3 = ['Thursday 27 Jan 2017']
assert get_day(assignment_dates3)
print(get_day(assignment_dates3))

['Thursday']


#### Question 7
Complete the get_day_numbers function to return the INTEGER values for the numbers in the date

E.g. get_day_numbers(['Tue 23 April 2017']) = [23]

In [33]:
def get_day_numbers(date_list):
    return [int(date.split()[1]) for date in date_list]


In [34]:
# Test1
assignment_dates = ['Friday 30 Jan 2017', 'Saturday 19 March 2016', 'Sunday 10 October 2015']
assert get_day_numbers(assignment_dates)

print(get_day_numbers(assignment_dates))


[30, 19, 10]


In [10]:
# Test2
assignment_dates2 = ['Monday 17 Jan 2017', 'Tuesday 1 March 2016', 'Wednesday 30 October 2015']
assert get_day_numbers(assignment_dates2)

print(get_day_numbers(assignment_dates2))

[17, 1, 30]


#### Question 8
Complete the function to get the year in the date. Make sure this stays a string not an Integer

In [4]:

def get_years(date_list):
    return [date.split()[-1] for date in date_list]


In [11]:
# Test1
assignment_dates = ['Friday 27 Jan 2017', 'Saturday 12 March 2016', 'Sunday 3 October 2015']
assert get_years(assignment_dates) 
print(get_years(assignment_dates))


['2017', '2016', '2015']


In [12]:
# Test2
assignment_dates4 = ['Monday 17 Jan 2000', 'Tuesday 1 March 1998', 'Wednesday 30 October 2043']
assert get_years(assignment_dates4)
print(get_years(assignment_dates4))

['2000', '1998', '2043']


### Part B: Numpy

Consider the array below

In [2]:
import numpy as np

In [3]:
a = np.random.rand(4,5)
a

array([[0.5602076 , 0.58934562, 0.90658525, 0.79266395, 0.29759283],
       [0.45451755, 0.38554837, 0.90007169, 0.85081396, 0.9616947 ],
       [0.98338119, 0.96519991, 0.74784715, 0.71343264, 0.02709132],
       [0.65838204, 0.44513954, 0.98074345, 0.02461114, 0.38649424]])

1. Generate an array called `ans1` comprising only the 2nd to 4th columns
2. Generate an array called `ans2` of just the 1st to 3rd columns and the 2nd to 3rd rows
3. What is the mean and standard deviation of the rows in array a (Name them `arows_mean`, `arows_sd`)
4. Calculate the mean and variance of the columns in array a (Name them `acols_mean`, `acols_var`)

In [4]:

import numpy as np
a = np.random.rand(4,5)
ans1 = a[:, 1:4]
print(ans1)

[[0.35497008 0.95390328 0.45044047]
 [0.43807338 0.94003489 0.44337292]
 [0.48313577 0.5372849  0.03129841]
 [0.01628775 0.94540743 0.79896787]]


In [5]:

import numpy as np 

ans2 = a[1:3, 0:3]

# Print the result
print(ans2)


[[0.69531253 0.43807338 0.94003489]
 [0.18415959 0.48313577 0.5372849 ]]


In [6]:

import numpy as np
arows_mean = np.mean(a, axis=1)
arows_sd = np.std(a, axis=1)

# Print the results
print("Mean of the rows:", arows_mean)
print("Standard deviation of the rows:", arows_sd)




Mean of the rows: [0.47196967 0.60496132 0.32460077 0.62064193]
Standard deviation of the rows: [0.28577562 0.19172847 0.18975099 0.38035421]


In [7]:
import numpy as np
acols_mean = np.mean(a, axis=0)
acols_var = np.var(a, axis=0)

# Print the results
print("Mean of the columns:", acols_mean)
print("Variance of the columns:", acols_var)

Mean of the columns: [0.60157876 0.32311675 0.84415763 0.43101992 0.32784405]
Variance of the columns: [0.08676193 0.03349495 0.03141474 0.07392318 0.02523915]


Use numpy to load up the datafile `irisdata.txt`. Also load up the labels that correspond to this file `irislabels.txt`

In [8]:
import numpy as np

# Load the data from irisdata.txt
data_file_path = 'irisdata.txt' 
iris_data = np.loadtxt(data_file_path, delimiter=',')

# Load the labels from irislabels.txt
labels_file_path = 'irislabels.txt' 
iris_labels = np.loadtxt(labels_file_path, dtype=int)

# Print the loaded data and labels
print("Iris Data:\n", iris_data)
print("\nIris Labels:\n", iris_labels)


Iris Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]


C:\Users\user\AppData\Local\Temp\ipykernel_6900\2336837699.py:9: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  iris_labels = np.loadtxt(labels_file_path, dtype=int)


1. What are the size of the data from the datafile? 
2. The irislabels file has the labels or classes corresponding to the data what are the sizes of the different classes ?

In [9]:
data_size = iris_data.shape
print("Size of the data:", data_size)


unique_classes, class_counts = np.unique(iris_labels, return_counts=True)
class_sizes = dict(zip(unique_classes, class_counts))
print("\nSizes of different classes:")
for class_label, class_size in class_sizes.items():
    print(f"Class {class_label}: {class_size}")

Size of the data: (150, 4)

Sizes of different classes:
Class 0: 50
Class 1: 50
Class 2: 50


#### Manually building a prototype based classifier

A prototype classifier obtains a very good representative of each class - also called a prototype and uses this for the classification task by computing the distance between a test set and the prototypes of each class. We are going to try and build one using this data.

To start this we need to split our data into a training and test set. 

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split



ModuleNotFoundError: No module named 'sklearn'

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Now we want to get the prototypes. This process can be complicated but for now lets just get the average of each of the data examples representing each class. 

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Now lets see how well your algorithm performs

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

### Part C: Pandas - some data analytics tasks

Load the dataset `uganda_produce.csv` using pandas `pandas.read_csv`

In [1]:
import pandas as pd
df = pd.read_csv("uganda_produce.csv")

**Questions**

1. How many unique items are there in the dataset (Hint: you may want to investigate the `unique` method of pandas)
3. Of these products [sweet potatoes, beans and cassava] which had the highest yield overall ? What about for the year 2006 alone ?
2. Which commodity(item) overall had the highest area harvested ?
4. Plot the trend of area harvested for bananas over the years

In [10]:
unique_items_all_columns = df.stack().unique()

# Print the unique items across all columns
print("Unique items across all columns:")
print(unique_items_all_columns)

Unique items across all columns:
['Uganda' 'Bananas' 'Area Harvested' ... 92200.0 87100.0 80300.0]


In [19]:


# Display the first few rows of the dataset to understand its structure
print(df.head())

max_production_row = df.loc[df['Value'].idxmax()]

# Print information about the row with the highest production
print("Row with the highest production:")
print(max_production_row)


  country     item         element Unit                  Date     Value
0  Uganda  Bananas  Area Harvested   Ha  1/1/2003 12:00:00 AM  140323.0
1  Uganda  Bananas  Area Harvested   Ha  1/1/2004 12:00:00 AM  141083.0
2  Uganda  Bananas  Area Harvested   Ha  1/1/2005 12:00:00 AM  141505.0
3  Uganda  Bananas  Area Harvested   Ha  1/1/2006 12:00:00 AM  141674.0
4  Uganda  Bananas  Area Harvested   Ha  1/1/2007 12:00:00 AM  141758.0
Row with the highest production:
country                               Uganda
item       Fruit excl Melons,Total + (Total)
element                  Production Quantity
Unit                                  tonnes
Date                    1/1/2003 12:00:00 AM
Value                             10357475.0
Name: 528, dtype: object


In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()